<?php
/**
 * Verify fix untuk "Sebagian Dikembalikan" -> "Dikembalikan" status issue
 */

require_once 'api/koneksi.php';
require_once 'api/session-helper.php';

echo "=== Verifying Status Fix ===\n\n";

// Test 1: Find a peminjaman with status 'Dikembalikan'
echo "1. Finding peminjaman with status 'Dikembalikan'...\n";
$stmt = $conn->prepare("
    SELECT p.id, p.kode_peminjaman, p.status, p.nama_peminjam, p.user_id
    FROM peminjaman p
    WHERE p.status = 'Dikembalikan'
    LIMIT 1
");
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows > 0) {
    $peminjaman = $result->fetch_assoc();
    echo "   ✓ Found: ID={$peminjaman['id']}, Kode={$peminjaman['kode_peminjaman']}, Status={$peminjaman['status']}\n";
    
    // Test 2: Check if there are detail_peminjaman items
    echo "\n2. Checking detail_peminjaman items...\n";
    $stmt2 = $conn->prepare("
        SELECT COUNT(*) as total_items
        FROM detail_peminjaman
        WHERE peminjaman_id = ?
    ");
    $stmt2->bind_param("i", $peminjaman['id']);
    $stmt2->execute();
    $items = $stmt2->get_result()->fetch_assoc();
    echo "   ✓ Total items borrowed: {$items['total_items']}\n";
    
    // Test 3: Check if there's any pengembalian pending
    echo "\n3. Checking pengembalian status...\n";
    $stmt3 = $conn->prepare("
        SELECT id, status FROM pengembalian
        WHERE peminjaman_id = ?
        ORDER BY id DESC LIMIT 1
    ");
    $stmt3->bind_param("i", $peminjaman['id']);
    $stmt3->execute();
    $peng = $stmt3->get_result()->fetch_assoc();
    
    if ($peng) {
        echo "   ✓ Last pengembalian: Status={$peng['status']}\n";
    } else {
        echo "   ℹ No pengembalian records yet\n";
    }
    
    // Test 4: Verify that this peminjaman would now be accepted in return.php
    echo "\n4. Verifying return.php would now accept this peminjaman...\n";
    $allowedStatuses = ['Sedang Dipinjam', 'Dikembalikan', 'Proses Return'];
    if (in_array($peminjaman['status'], $allowedStatuses, true)) {
        echo "   ✓ Status '{$peminjaman['status']}' is now ALLOWED for return submission\n";
        echo "   ✓ User can now submit return request without error\n";
    } else {
        echo "   ✗ Status '{$peminjaman['status']}' still not allowed\n";
    }
    
} else {
    echo "   ℹ No peminjaman with status 'Dikembalikan' found\n";
    echo "   This means user might not have peminjaman ready for partial returns yet\n";
}

echo "\n=== Summary ===\n";
echo "Fix applied:\n";
echo "  - Added 'Dikembalikan' to allowedStatuses in return.php\n";
echo "  - Removed non-existent 'Sebagian Dikembalikan' from hardcoded validation\n";
echo "  - Status check now matches actual database enum values\n";
echo "\nBefore: Only 'Sedang Dipinjam', 'Sebagian Dikembalikan', 'Proses Return'\n";
echo "After:  Only 'Sedang Dipinjam', 'Dikembalikan', 'Proses Return'\n";
echo "\nNote: 'Sebagian Dikembalikan' displayed in UI is auto-generated by get_all.php\n";
echo "      based on pengembalian records, not a direct database status.\n";
?>
