@extends('layouts.app')
@section('title','Buat Laporan - LAPORIN')
@section('meta_title','LAPORIN SMK Taruna Bangsa Bekasi | Lapor Perundungan')
@section('meta_description','Buat laporan perundungan, pembullyan, pelanggaran siswa, atau kerusakan fasilitas SMK Taruna Bangsa Bekasi secara aman dan terlacak.')
@section('canonical'){{ url('/') }}@endsection
@section('content')
@php
    $today = date('Y-m-d');
    $wizardStep = (int) ($wizardStep ?? 1);
    $reportType = old('report_type', $wizardStep > 1 ? (session('report_submit_forms.'.session('report_submit_token').'.wizard_data.report_type') ?? 'violation') : 'violation');
    $reportSubmitToken = $reportSubmitToken ?? session('report_submit_token');
@endphp
<form id="form-laporan" method="POST" action="{{ route('public.report.step.store', $wizardStep) }}" enctype="multipart/form-data">
@csrf
<input type="hidden" name="report_submit_token" value="{{ $reportSubmitToken ?? session('report_submit_token') }}">
<div class="laporin-card mb-3 step-track"><div class="row g-2 text-center">@foreach([1=>'Identitas',2=>'Jenis',3=>'Detail',4=>'Kirim'] as $n=>$label)<div class="col"><div class="step-dot-wrapper"><button type="button" class="step-dot{{ $n <= $wizardStep ? ' active' : '' }}" data-step-dot="{{ $n }}" style="min-width:44px;min-height:44px;" aria-label="Langkah {{ $n }}">{{ $n }}</button></div><div class="small mt-2 fw-semibold">{{ $label }}</div></div>@endforeach</div><p class="mt-3 mb-0 text-center small" data-step-hint>Isi lengkap, lalu lanjut ke tahap berikutnya.</p></div>
@if($errors->any())<div class="alert alert-danger mt-3 mb-3" id="step-error-alert" role="alert"><strong class="d-block mb-1">Lengkapi formulir dengan benar</strong><ul class="mb-0 ps-3">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="laporin-card wizard-panel p-3 p-md-4 p-lg-5">
@if($wizardStep === 1)
<section data-step="1" class="wizard-step is-active"><span class="page-kicker">Langkah 1</span><h2 class="h4 fw-bold mt-2 mb-1">Identitas Pelapor</h2><p class="small-muted mb-4">Isi yang paling penting saja.</p><div class="row g-3">
<div class="col-12"><label class="form-label required" for="reporter_name">Nama Pelapor</label><input id="reporter_name" name="reporter_name" value="{{ old('reporter_name') }}" class="form-control required" required maxlength="150" autocomplete="name" placeholder="Nama lengkap"></div>
<div class="col-12 col-md-6"><label class="form-label required" for="reporter_class_id">Kelas</label><select id="reporter_class_id" name="reporter_class_id" class="form-select required" required><option value="">Pilih kelas</option>@include('public.partials.class-options', ['selectedClassId' => old('reporter_class_id')])</select><small class="text-muted">Dikelompokkan per jurusan dan diurutkan.</small></div>
<div class="col-12 col-md-6"><label class="form-label" for="reporter_absence_number">No. Absen</label><input id="reporter_absence_number" type="number" name="reporter_absence_number" value="{{ old('reporter_absence_number') }}" min="1" max="60" class="form-control" placeholder="1–60"></div>
<div class="col-12 col-md-6"><label class="form-label required" for="reporter_phone">No. HP</label><input id="reporter_phone" name="reporter_phone" value="{{ old('reporter_phone') }}" class="form-control required" required maxlength="30" pattern="[0-9+() .\-]+" inputmode="tel" autocomplete="tel" placeholder="Contoh: 0812 3456 7890"><small class="text-muted">Nomor HP wajib diisi. Gunakan 8-15 digit.</small></div>
<div class="col-12 col-md-6"><label class="form-label" for="reporter_email">Email</label><input id="reporter_email" type="email" name="reporter_email" value="{{ old('reporter_email') }}" class="form-control" maxlength="150" autocomplete="email" placeholder="Contoh: nama@email.com"><small class="text-muted">Opsional. Jika diisi, email digunakan untuk notifikasi status laporan.</small></div>
</div></section>
@endif
@if($wizardStep === 2)
<section data-step="2" class="wizard-step laporin-card p-3 p-md-4 p-lg-5 is-active"><span class="page-kicker">Langkah 2</span><h2 class="h4 fw-bold mt-2 mb-1">Pilih Jenis Laporan</h2><p class="small-muted mb-4">Pilih satu jenis laporan yang paling sesuai.</p><div class="row g-3"><div class="col-md-6"><label class="choice-card p-4 w-100{{ $reportType === 'violation' ? ' is-selected' : '' }}"><input type="radio" name="report_type" value="violation" required @checked($reportType === 'violation')><strong class="d-block mt-2">Perundungan / Pelanggaran</strong><span class="small-muted">Untuk perundungan, pembullyan, atau pelanggaran tata tertib. Ditangani oleh Kesiswaan.</span></label></div><div class="col-md-6"><label class="choice-card p-4 w-100{{ $reportType === 'damage' ? ' is-selected' : '' }}"><input type="radio" name="report_type" value="damage" required @checked($reportType === 'damage')><strong class="d-block mt-2">Kerusakan Fasilitas</strong><span class="small-muted">Untuk kerusakan meja, proyektor, AC, toilet, pintu, dll. Ditangani oleh Sarpras.</span></label></div></div></section>
@endif
@if($wizardStep === 3)
<section data-step="3" class="wizard-step laporin-card p-3 p-md-4 p-lg-5 is-active"><span class="page-kicker">Langkah 3</span><h2 class="h4 fw-bold mt-2 mb-1">Detail Kejadian</h2><p class="small-muted mb-4">Isi singkat dan jelas.</p><div class="row g-3">
<div class="col-12"><label class="form-label required" for="title">Judul singkat</label><input id="title" name="title" value="{{ old('title') }}" class="form-control required" required maxlength="200" placeholder="{{ $reportType === 'violation' ? 'Contoh: Perundungan di Lab Komputer' : 'Contoh: Lampu kelas X Mati' }}"></div>
<div class="col-12 col-md-6"><label class="form-label required" for="urgency">Tingkat Urgensi</label><select id="urgency" name="urgency" class="form-select required" required>@foreach(['rendah','sedang','tinggi','darurat'] as $urgency)<option value="{{ $urgency }}" @selected(old('urgency','sedang') === $urgency)>{{ match($urgency){'rendah'=>'Rendah','sedang'=>'Sedang','tinggi'=>'Tinggi','darurat'=>'Darurat'} }}</option>@endforeach</select></div>
<div class="col-12 col-md-6"><label class="form-label required" for="incident_date">Tanggal kejadian</label><input id="incident_date" type="date" name="incident_date" value="{{ old('incident_date') }}" max="{{ $today }}" class="form-control required" required><small class="text-muted">Tanggal saat kejadian berlangsung (tidak boleh di masa depan).</small></div>
<div class="col-12{{ $reportType === 'violation' ? '' : ' d-none' }}" data-report-type-content="violation"><fieldset class="border-0 p-0 m-0" {{ $reportType === 'violation' ? '' : 'disabled' }}><div class="detail-box"><h3 class="h6 fw-bold mb-3">Detail pelanggaran</h3><div class="row g-3"><div class="col-12"><label class="form-label required" for="related_class_id">Kelas pelaku</label><select id="related_class_id" name="related_class_id" class="form-select" required><option value="">Pilih kelas</option>@include('public.partials.class-options', ['selectedClassId' => old('related_class_id')])</select></div><div class="col-12"><label class="form-label required" for="alleged_actor_name">Nama terduga pelaku</label><input id="alleged_actor_name" name="alleged_actor_name" value="{{ old('alleged_actor_name') }}" class="form-control required" required maxlength="150"></div><div class="col-12"><label class="form-label" for="alleged_actor_class_id">Kelas terduga pelaku</label><select id="alleged_actor_class_id" name="alleged_actor_class_id" class="form-select"><option value="">Pilih kelas (opsional)</option>@include('public.partials.class-options', ['selectedClassId' => old('alleged_actor_class_id')])</select></div><div class="col-12"><label class="form-label required" for="description">Kronologi singkat</label><textarea id="description" name="description" class="form-control required" rows="4" required maxlength="5000">{{ old('description') }}</textarea></div></div></div></fieldset></div>
<div class="col-12{{ $reportType === 'damage' ? '' : ' d-none' }}" data-report-type-content="damage"><fieldset class="border-0 p-0 m-0" {{ $reportType === 'damage' ? '' : 'disabled' }}><div class="detail-box"><h3 class="h6 fw-bold mb-3">Detail kerusakan</h3><div class="row g-3"><div class="col-12 col-md-6"><label class="form-label required" for="item_name">Nama barang / fasilitas</label><input id="item_name" name="item_name" value="{{ old('item_name') }}" class="form-control required" required maxlength="150"></div><div class="col-12 col-md-6"><label class="form-label" for="location_id_damage">Lokasi</label><select id="location_id_damage" name="location_id" class="form-select"><option value="">Pilih lokasi</option>@foreach($locations as $l)<option value="{{ $l->id }}" @selected(old('location_id') == $l->id)>{{ $l->location_name }}</option>@endforeach</select></div><div class="col-12"><label class="form-label required" for="damage_condition">Kondisi kerusakan</label><textarea id="damage_condition" name="damage_condition" class="form-control required" rows="4" maxlength="2000" required>{{ old('damage_condition') }}</textarea></div><div class="col-12"><label class="form-label required" for="description_damage">Deskripsi dampak</label><textarea id="description_damage" name="description" class="form-control required" rows="4" required maxlength="5000">{{ old('description') }}</textarea></div></div></div></fieldset></div>
</div></section>
@endif
@if($wizardStep === 4)
<section data-step="4" class="wizard-step laporin-card p-3 p-md-4 p-lg-5 is-active"><span class="page-kicker">Langkah 4</span><h2 class="h4 fw-bold mt-2 mb-1">Konfirmasi & Kirim</h2><p class="small-muted mb-4">Cek ulang, lalu kirim.</p><div class="row g-3"><div class="col-12"><div class="detail-box"><h3 class="h6 fw-bold mb-3">Bukti Foto / Dokumen (Opsional)</h3><label class="form-label" for="attachments">Unggah Bukti</label><input id="attachments" type="file" name="attachments[]" class="form-control" multiple accept=".jpg,.jpeg,.png,.webp,.pdf,image/jpeg,image/png,image/webp,application/pdf"><small class="text-muted">Maksimal 3 file; JPG, PNG, WEBP, atau PDF; maksimal 4MB per file.</small></div></div><div class="col-12"><div class="detail-box"><div class="form-check mt-3"><input class="form-check-input" type="checkbox" name="consent" value="1" id="consent" required @checked(old('consent') === '1')><label class="form-check-label required" for="consent">Saya menyatakan laporan adalah benar</label></div></div></div><div class="col-12 col-md-6"><label class="form-label required" for="captcha">CAPTCHA: berapa {{ $captchaQuestion }}?</label><input id="captcha" name="captcha" value="{{ old('captcha') }}" class="form-control required" required inputmode="numeric" pattern="[0-9]+" maxlength="2"></div></div></section>
@endif
</div>
<div class="bottom-action mt-4"><div class="row g-2 align-items-center w-100"><div class="col-12 col-sm"><span class="small-muted">@if($wizardStep === 4)Periksa kembali seluruh isian, lalu kirim laporan.@else Isi lengkap, lalu lanjut ke langkah berikutnya.@endif</span></div><div class="col-12 col-sm-auto"><div class="d-flex gap-2 flex-wrap">@if($wizardStep > 1)<a href="{{ route('public.report.step',$wizardStep-1) }}" class="btn btn-outline-laporin" style="min-height:44px;">Kembali</a>@endif<button type="submit" class="btn btn-laporin" style="min-height:44px;">{{ $wizardStep < 4 ? 'Lanjut' : 'Kirim Laporan' }}</button></div></div></div></div>
</form>
@endsection
@push('head')
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'WebSite','name'=>'LAPORIN SMK Taruna Bangsa Bekasi','url'=>url('/')], JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) !!}</script>
@endpush
@push('scripts')<script src="{{ asset('js/laporin-report-fix.js') }}?v={{ filemtime(public_path('js/laporin-report-fix.js')) }}" defer></script>@endpush
