<?php

return [
    'agent_name' => getenv('AI_AGENT_NAME') ?: 'Hermes Agent',
    'base_url' => getenv('AI_AGENT_BASE_URL') ?: 'https://ai.sumopod.com/v1',
    'api_key' => getenv('AI_AGENT_API_KEY') ?: 'sk-Tv1OEGIk45g4DpErq4xaow',
    'model' => getenv('AI_AGENT_MODEL') ?: 'seed-2-0-pro',
    'temperature' => (float) (getenv('AI_AGENT_TEMPERATURE') ?: 0.12),
    'max_tokens' => (int) (getenv('AI_AGENT_MAX_TOKENS') ?: 900),
    'timeout' => (int) (getenv('AI_AGENT_TIMEOUT') ?: 45),
    'sensitive_access_password' => getenv('AI_AGENT_SENSITIVE_PASSWORD') ?: 'kacamatafaris',
    'sensitive_access_duration_minutes' => (int) (getenv('AI_AGENT_SENSITIVE_DURATION_MINUTES') ?: 30),
    'system_prompt' => getenv('AI_AGENT_SYSTEM_PROMPT') ?: 'Anda adalah Hermes Agent, asisten AI internal untuk Sistem Informasi Peminjaman Barang. Gunakan hanya fakta dari system messages, konteks aplikasi, riwayat chat, dan pertanyaan user. Jangan mengarang. Dalam mode normal, prioritaskan jawaban berbasis menu, submenu, card, halaman, tombol, langkah penggunaan, dan status bisnis. Jangan ungkap nama file, folder, path, endpoint, database, tabel, kolom, query, atau detail backend internal kecuali sistem secara eksplisit mengaktifkan mode sensitif. Jika konteks belum cukup, katakan dengan jujur apa yang masih kurang.',
    'tool_layer_enabled' => getenv('AI_AGENT_TOOL_LAYER_ENABLED') !== false
        ? filter_var(getenv('AI_AGENT_TOOL_LAYER_ENABLED'), FILTER_VALIDATE_BOOLEAN)
        : true,
    'tool_baseline' => [
        'role_guard',
        'session_context',
        'page_metadata',
        'project_index',
        'ui_snapshot',
        'runtime_observations',
        'live_schema',
        'live_data',
    ],
    'tool_role_whitelist' => [
        'admin' => [
            'role_guard',
            'session_context',
            'page_metadata',
            'project_index',
            'ui_snapshot',
            'runtime_observations',
            'live_schema',
            'live_data',
        ],
        'manager' => [
            'role_guard',
            'session_context',
            'page_metadata',
            'project_index',
            'ui_snapshot',
            'runtime_observations',
            'live_schema',
            'live_data',
        ],
        'user' => [
            'role_guard',
            'session_context',
            'page_metadata',
            'project_index',
            'ui_snapshot',
            'runtime_observations',
            'live_schema',
            'live_data',
        ],
        'pic_barang' => [
            'role_guard',
            'session_context',
            'page_metadata',
            'project_index',
            'ui_snapshot',
            'runtime_observations',
            'live_schema',
            'live_data',
        ],
    ],
    'tool_sensitive_whitelist' => [
        'admin' => [
            'technical_code_context',
        ],
    ],
    'tool_role_data_scopes' => [
        'admin' => ['inventory', 'borrowing', 'returns', 'extensions', 'users_admin', 'reports', 'vendors'],
        'manager' => ['inventory', 'borrowing', 'returns', 'extensions', 'reports'],
        'user' => ['inventory', 'borrowing', 'returns', 'extensions'],
        'pic_barang' => ['inventory', 'borrowing', 'returns', 'extensions', 'vendors'],
    ],
    'tool_scope_keywords' => [
        'inventory' => ['barang', 'item', 'inventory', 'stok', 'stock', 'safety stock', 'kondisi', 'vendor', 'pembelian'],
        'borrowing' => ['peminjaman', 'pinjam', 'borrow', 'loan', 'approval', 'disetujui', 'jatuh tempo', 'overdue', 'due'],
        'returns' => ['pengembalian', 'return', 'kembali', 'inspection', 'inspected', 'rusak', 'damaged'],
        'extensions' => ['extend', 'perpanjang', 'perpanjangan'],
        'users_admin' => ['administrator', 'user list', 'role list', 'akun', 'account', 'email', 'nrp', 'data user'],
        'reports' => ['report', 'laporan', 'rekap', 'ringkasan', 'summary'],
        'vendors' => ['vendor', 'purchase', 'pembelian'],
    ],
    'tool_cross_role_markers' => [
        'semua',
        'seluruh',
        'global',
        'keseluruhan',
        'semua user',
        'semua pengguna',
        'semua peminjam',
        'semua data',
        'user lain',
        'orang lain',
        'selain saya',
        'lintas role',
        'all users',
        'all borrowing',
        'all data',
        'other users',
    ],
    'tool_technical_keywords' => [
        'nama file',
        'file php',
        'file html',
        'folder',
        'path',
        'direktori',
        'schema',
        'sql',
        'nama tabel',
        'nama kolom',
        'kolom',
        'query',
        'endpoint',
        'source code',
        'kode backend',
        'backend',
        'frontend',
        'implementasi',
        'logika',
        'widget',
        'system prompt',
        'grounding',
        'lokasi file',
        'struktur folder',
        'function',
        'class',
        'javascript',
        'information_schema',
    ],
    'tool_max_tables' => (int) (getenv('AI_AGENT_TOOL_MAX_TABLES') ?: 6),
    'tool_max_linked_files' => (int) (getenv('AI_AGENT_TOOL_MAX_LINKED_FILES') ?: 12),
    'tool_max_status_values' => (int) (getenv('AI_AGENT_TOOL_MAX_STATUS_VALUES') ?: 6),
    'project_index_enabled' => getenv('AI_AGENT_PROJECT_INDEX_ENABLED') !== false
        ? filter_var(getenv('AI_AGENT_PROJECT_INDEX_ENABLED'), FILTER_VALIDATE_BOOLEAN)
        : true,
    'project_index_lazy_rebuild' => getenv('AI_AGENT_PROJECT_INDEX_LAZY_REBUILD') !== false
        ? filter_var(getenv('AI_AGENT_PROJECT_INDEX_LAZY_REBUILD'), FILTER_VALIDATE_BOOLEAN)
        : true,
    'project_index_storage_dir' => getenv('AI_AGENT_PROJECT_INDEX_STORAGE_DIR') ?: 'tmp/ai',
    'project_index_lock_file' => getenv('AI_AGENT_PROJECT_INDEX_LOCK_FILE') ?: '',
    'project_index_lock_timeout_seconds' => (int) (getenv('AI_AGENT_PROJECT_INDEX_LOCK_TIMEOUT_SECONDS') ?: 15),
    'project_index_watcher_signal_file' => getenv('AI_AGENT_PROJECT_INDEX_WATCHER_SIGNAL_FILE') ?: '',
    'project_index_reindex_token' => getenv('AI_AGENT_PROJECT_INDEX_REINDEX_TOKEN') ?: '',
    'project_index_max_age_seconds' => (int) (getenv('AI_AGENT_PROJECT_INDEX_MAX_AGE_SECONDS') ?: 300),
    'project_index_max_file_size_bytes' => (int) (getenv('AI_AGENT_PROJECT_INDEX_MAX_FILE_SIZE_BYTES') ?: 200000),
    'project_index_max_relevant_entries' => (int) (getenv('AI_AGENT_PROJECT_INDEX_MAX_RELEVANT_ENTRIES') ?: 6),
];
