<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta name="x-apple-disable-message-reformatting">
    <title>LAPORIN — Laporan {{ $reportNumber }} diterima</title>
</head>
<body style="margin:0;padding:0;background:#f3f6f9;color:#17212b;font-family:Arial,Helvetica,sans-serif;-webkit-text-size-adjust:100%;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f3f6f9;">
<tr><td align="center" style="padding:32px 12px;">
<table role="presentation" width="640" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:640px;background:#ffffff;border:1px solid #e5eaf0;border-radius:16px;overflow:hidden;">
<tr><td style="padding:22px 30px;background:#0f766e;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td style="width:72px;vertical-align:middle;"><img src="{{ $message->embed(public_path('images/branding/logo tb.png')) }}" alt="Logo SMK Taruna Bangsa" width="58" height="58" style="display:block;width:58px;height:58px;object-fit:contain;background:#ffffff;border-radius:12px;padding:5px;"></td><td style="padding-left:14px;font-size:22px;line-height:28px;font-weight:700;color:#ffffff;letter-spacing:.2px;">LAPORIN</td><td align="right" style="font-size:12px;line-height:18px;color:#d7fffa;">SMK Taruna Bangsa Bekasi</td></tr></table></td></tr>
<tr><td style="padding:34px 34px 12px;"><div style="display:inline-block;padding:7px 12px;border-radius:999px;background:#e7f7f4;color:#0f766e;font-size:12px;line-height:16px;font-weight:700;letter-spacing:.4px;">LAPORAN DITERIMA</div><h1 style="margin:16px 0 10px;font-size:28px;line-height:36px;color:#17212b;">Laporan Anda berhasil dikirim</h1><p style="margin:0;color:#52606d;font-size:16px;line-height:25px;">Yth. <strong style="color:#17212b;">{{ $report->reporter_name }}</strong>, laporan Anda telah diterima oleh sistem LAPORIN dan menunggu proses verifikasi.</p></td></tr>
<tr><td style="padding:22px 34px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#f8fafb;border:1px solid #e3e9ee;border-radius:12px;"><tr><td style="padding:20px 22px;"><div style="font-size:11px;line-height:16px;color:#6b7785;text-transform:uppercase;letter-spacing:1.1px;font-weight:700;">Nomor Laporan</div><div style="margin-top:6px;font-size:22px;line-height:30px;font-weight:700;color:#17212b;word-break:break-word;">{{ $reportNumber }}</div><div style="margin-top:18px;height:1px;background:#e3e9ee;"></div><div style="margin-top:18px;font-size:11px;line-height:16px;color:#6b7785;text-transform:uppercase;letter-spacing:1.1px;font-weight:700;">Kode Akses</div><div style="margin-top:6px;font-size:24px;line-height:32px;font-weight:700;letter-spacing:3px;color:#0f766e;">{{ $accessCode }}</div></td></tr></table></td></tr>
<tr><td style="padding:0 34px 24px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;"><tr><td colspan="2" style="padding:0 0 12px;font-size:14px;font-weight:700;color:#17212b;">Ringkasan laporan</td></tr><tr><td style="padding:10px 0;border-top:1px solid #edf0f2;width:38%;font-size:13px;color:#6b7785;">Jenis</td><td style="padding:10px 0;border-top:1px solid #edf0f2;font-size:14px;font-weight:600;color:#17212b;">{{ $reportTypeLabel }}</td></tr><tr><td style="padding:10px 0;border-top:1px solid #edf0f2;font-size:13px;color:#6b7785;">Judul</td><td style="padding:10px 0;border-top:1px solid #edf0f2;font-size:14px;font-weight:600;color:#17212b;">{{ $report->title }}</td></tr><tr><td style="padding:10px 0;border-top:1px solid #edf0f2;font-size:13px;color:#6b7785;">Status</td><td style="padding:10px 0;border-top:1px solid #edf0f2;font-size:14px;font-weight:700;color:#0f766e;">{{ $statusLabel }}</td></tr><tr><td style="padding:10px 0;border-top:1px solid #edf0f2;font-size:13px;color:#6b7785;">Dikirim</td><td style="padding:10px 0;border-top:1px solid #edf0f2;font-size:14px;font-weight:600;color:#17212b;">{{ $report->created_at?->format('d/m/Y H:i') ?? '-' }} WIB</td></tr></table></td></tr>
<tr><td style="padding:0 34px 30px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#fff8e6;border:1px solid #f3dfaa;border-radius:12px;"><tr><td style="padding:16px 18px;font-size:13px;line-height:21px;color:#5f4b18;"><strong>Jaga kerahasiaan kode akses.</strong><br>Kode ini digunakan bersama nomor laporan untuk melihat perkembangan laporan Anda.</td></tr></table></td></tr>
<tr><td align="center" style="padding:0 34px 34px;"><a href="{{ url('/lacak') }}" style="display:inline-block;padding:13px 24px;background:#0f766e;color:#ffffff;text-decoration:none;border-radius:9px;font-size:14px;line-height:20px;font-weight:700;">Lacak Laporan</a><p style="margin:12px 0 0;font-size:12px;line-height:18px;color:#7b8794;">{{ url('/lacak') }}</p></td></tr>
<tr><td style="padding:22px 30px;background:#f8fafb;border-top:1px solid #e8edf1;text-align:center;"><div style="font-size:12px;line-height:18px;font-weight:700;color:#52606d;">LAPORIN · SMK Taruna Bangsa Bekasi</div><div style="margin-top:5px;font-size:11px;line-height:17px;color:#8994a0;">Kanal pelaporan perundungan, pelanggaran, dan kerusakan fasilitas.</div><div style="margin-top:10px;font-size:11px;line-height:17px;color:#a0a9b2;">Email ini dikirim secara otomatis. Mohon tidak membalas email ini.</div></td></tr>
</table></td></tr></table>
</body>
</html>
